### ISSUE TITLE
Wich crewstation the players is in, for multicrew modules (Enhancement)

### ISSUE THREAD

**Issue by flanker0ne** [DCSFlightpanels/dcs-bios#129]
My point is the ability to move from Pilot and CPG in the AH-64D, and read the correct output from Keyboard Unit and EUFD

**Comment by WarLord211** [comment]
there is no readout for the Position in cockpit.
Sorry dont know how to archive this

**Comment by flanker0ne** [comment]
Ok, thank for the answer and for the great work mantaining this.

**Comment by flanker0ne** [comment]
In recent DCS version, if I open the Setup Controls and I'm on the CPG seat, DCS recognise my position and show the correct menù.
It's that event sufficient to allow DCS BIOS, to automatically recognise the player seat?

**Comment by Maverick87Shaka** [comment]
> In recent DCS version (maybe just in Closed Beta), if I open the Setup Controls and I'm on the CPG seat, DCS recognize my position and show the correct menu.
> It's that event sufficient to allow DCS BIOS, to automatically recognize the player seat?

As far as i understood, the DCS BIOS can read only "cockpit arguments" variables allowed by export.lua logic of native DCS.
Since some release adjust controls are opened on the correct seat, but it looks like DCS UI to do that access a variable placed in another "environment space", so DCS BIOS can't read this information.
