### ISSUE TITLE
F/A18-C StandBy Altimeter "Baro Settings"

### ISSUE THREAD

**Issue by Lot2Learn2** [DCSFlightpanels/dcs-bios#139]
Hi,

I don't know much about coding, I may be wrong but I think there's a digit missing in Bios FP for the Baro Settings.

On the json file of the F/A18 I see a "Pressure Setting 0" that I don't have (missing) from DCS-BIOS control reference  FP,
not on the lua file. 

Since the Baro has 4 digits I figured out that my newbie theory makes sense.

Would you please have a look at this.

Thanks again,
Reg
![Screenshot 2023-01-08 110631](https://user-images.githubusercontent.com/122068962/211208027-f1109f6a-f419-4568-9d86-bacbfd2070e3.jpg)

**Comment by DeadMeatDCS** [comment]
@Lot2Learn2 yeah no it's not a bug. The previous fix didn't explain well I guess.

The pressure setting is measured in inches mercury with two decimals.
Pressure setting 1 is the hundredths counter ( _ _ . _ x)
Pressure setting 2 is the tenths counter ( _ _ . x _ )
Pressure setting 3 is the ones and tens counters together ( x x . _ _ )

If you observe it in DCS you'll see setting 3 is the two digits combined on a single counter drum and they move together: 28, 29, 30 and 31. 

26 and 27 is not available but it is in the code, which is why it never gets below the 40% in DCS-BIOS. Convert the reading into appropriate values:
40% (26214): 28
60% (39321): 29
80% (52428): 30
100% (65535): 31

By the way, remember to load all the way into the cockpit in DCS before looking at the command reference (json) after a DCS-BIOS update.

**Comment by Lot2Learn2** [comment]
Thanks for your answer, very well explained.
