### ISSUE TITLE
UH-1H Mapping for Cargo Release Safety missing

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#44]
The mapping for the cargo release safety on the overhead panel does not seem to exist. I think the entry should be something like
```
defineToggleSwitch("CARGO_REL", 12, ???, 228, "Overhead Panel", "Cargo Release OFF / ARM")
```
 but I just don't know enough about how these entries work to say for certain.

**Comment by WarLord211** [comment]
i look into this

**Comment by WarLord211** [comment]
Done! 
also fixed ADI pitch and Alt Trim
found some other missing switches
deleted one double entry.

may brake some existing arduino code of some switches because for this deletion.
see list:
CB_GYRO
CB_FUEL_QTY
CB_28V
CB_FAIL_RELAY
CB_FUEL
CB_TORQ
CB_XMSN
CB_ENG
CB_CRSIND
PITOT_HEAT
MAIN_GEN_SW
MAIN_GEN_COVER
CLP_RESET_TEST_SW
CLP_BRIGHT_DIM_SW
MAIN_FUEL_SW
TEST_FUEL_GAUGE_BTN
IFF_CODE
IFF_MASTER
IFF_OUT_AUDIO_LIGHT
IFF_TEST_M1
IFF_TEST_M2
IFF_TEST_M3
IFF_TEST_M4
IFF_RADTEST
IFF_MIC_IDENT
IFF_ON_OUT
IFF_MODE1_WHEEL1
IFF_MODE1_WHEEL2
IFF_MODE3A_WHEEL1
IFF_MODE3A_WHEEL2
IFF_MODE3A_WHEEL3
IFF_MODE3A_WHEEL4
IFF_REPLY_TEST
IFF_REPLY_DIM
IFF_TEST_TEST
IFF_TEST_DIM
CLOCK_ADJUST_PULL
CLOCK_ADJUST
THROTTLE
THROTTLE_STOP
ENG_DEICE
LOW_RPM_AUDIO
CHIP_DET_SW
EMER_GOV_SW
HYD_CONT_SW
FORCE_TRIM_SW
GOV_RPM_SW
FIRE_TEST_BTN
CPLT_ADI_CAGE

**Comment by charliefoxtwo** [comment]
I'm not sure if this is something you have control over, but I think the values are backwards. I expect `OFF` to be `0` and `ARM` to be `1`, however what I see is the opposite:
![image](https://user-images.githubusercontent.com/30303272/114262451-df918e80-9994-11eb-924c-1180ab6c0afa.png)
![image](https://user-images.githubusercontent.com/30303272/114262468-ee784100-9994-11eb-88d1-43689b2b084d.png)

This is the opposite of the way other switches in the same panel are configured, where anything that might signify off/lower power is 0, and anything that might signify on is 1.
![image](https://user-images.githubusercontent.com/30303272/114262500-27181a80-9995-11eb-945d-ec62f95bddb9.png)
![image](https://user-images.githubusercontent.com/30303272/114262512-39925400-9995-11eb-9438-91a0a6abdae2.png)

Other than that, the control seems to be working as expected (and no longer interfering with the `WIPER_SEL` control)

**Comment by WarLord211** [comment]
I saw that also. 
The 1 or 0 came from the Argument valve the switch has in that Position in the model.
For the cargo its switched in the Model.
i could change that if i programm an new switch and change the readings. 
But i saw not the Benefit/Work balance of it. 
if this is a priority problem i will do it !

**Comment by charliefoxtwo** [comment]
Difficult to say. On the one hand, the switch is inconsistent with the rest. On the other, if I understand you correctly this is a bug with the Huey (man, this thing has a lot of weird mapping issues).

I can work around it, so it's not an issue for me. I'll leave it up to you.

**Comment by WarLord211** [comment]
yes this thing has lot of messy code. ATM we live with it.
