### ISSUE TITLE
A-10C vs A-10C II

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#49]
DCS recently did some revamping of the A-10C and released it as the A-10C II. As far as I can tell dcs-bios works fine with it, but there is a small inconsistency: dcs-bios reports `ACFT_NAME` as `A-10C_2`, however it uses the same `A-10C` json files and lua files as far as I can tell.

I would suggest one of two solutions:
 - `A-10C_2.lua` file (this makes sense as DCS has separate mappings available for the A-10C vs the A-10C II, and treats them like separate aircraft, since I think the A-10C II has extra capabilities and things to map)
 - Change the `ACFT_NAME` that is output for the A-10C II to just be `A-10C`
 
To be clear: this isn't causing anything in dcs-bios to break currently. Some code that I wrote makes some assumptions about the data dcs-bios sends, and that has broken. If you feel dcs-bios should behave exactly as it does currently you're welcome to close this issue - but I do feel this is an inconsistency worth addressing.

**Comment by talbotmcinnis** [comment]
I wonder if this differentiation might become more important when/if the arc-210  radio is released and the controls do actually start to diverge?

**Comment by WarLord211** [comment]
At this point the code is 99% same. The switches chandes named as "A-10C 2"
And second lua with same code its not practical.

Atm its good as it is, since its works.

if the the modules begin to differ i would do it like the C101 and sepperate them by name. but i also musst think of existing cockpits so the changes are mostly in the description.

**Comment by charliefoxtwo** [comment]
If both aircraft are going to use the same json, is it possible for `ACFT_NAME` for the A-10C II to just be `A-10C`?

Also, I haven't tested this yet but does the L-39 do the same thing with the C/ZA models? I don't have the C-101 to test, I know nothing about the Gazelle, and I don't recall if the F-14A is out yet (and don't know much about it either). I do know the different L-39 models have different control mappings in DCS.

I guess the important thing is that the behavior is consistent across all modules.

**Comment by WarLord211** [comment]
ACFT_NAME comes from the module itself. I cant change this. With this name BIOS "loads" the lua.

F-14; L39; P51(TF-51), Gazelle all these works like these principe. one lua for "all aircraft of its type".
Its mentioned in the readme.

**Comment by charliefoxtwo** [comment]
Gotcha.

Does dcs-bios output anything else that might help me determine which json file to consider? My use case here is that I need to know what input types are available when translating commands to dcs-bios, and parsing that json file has been the easiest way to accomplish that for me. I've been selecting which file to parse based on `ACFT_NAME`, but clearly that's not a reliable way to do it.

**Comment by WarLord211** [comment]
i think i dont understand what you try to achieve.

Bios reads out the ACFT_NAME from this it choose the lua it needs. Json files are an translated form of the BIOS_PLANE.lua file.
I have combines simular Planes to one lua file to reduse work and size.
Also it improfes the performance because BIOS reads all lua files (as i understand)

why you dont do something lick me in the head of the lua files?

Example of A-10:

BIOS.protocol.setExportModuleAircrafts({"A-10C", "A-10C_2"})

these booth names work with this lua file

**Comment by charliefoxtwo** [comment]
Yeah I think that's what I'm going to have to do. I wanted to not have to worry about updating my application with the new aircraft names every time a variant is released and instead be able to rely on dcs-bios, but I don't think that will be possible now.

Not your fault or anything, just the nature of the architecture. I understand it's designed the way it is and it makes sense to me :)

I'll close this issue, since I don't think modifying dcs-bios will help and as far as I can tell it doesn't output the information I need would need to do this automatically and without manual configuration.

Thanks for taking a look!
